function EJM = EJM(j, P, q_up, q_down, e, p, zeta, c, l)
    EJM = sum(p.M(j,:).*sum(zeta(j).*(q_up + q_down).^2 ...
                            - squeeze(l.phi_up(:,j,:)).*q_up ...
                            - squeeze(l.phi_down(:,j,:)).*q_down), "all") ...
        + sum((1 - p.M(j,:)).*sum((squeeze(l.theta(:,j,:)) - c.sell.*ones(P,1)).*e), "all");
end

