function EJP = EJP(i, p_up, p_down, q_up, q_down, d, e, p, c, l)
    EJP = sum(c.sell.*p_up - c.buy.*p_down, "all") ...
        - sum(p.C.*squeeze(l.psi(i,:,:)).*d, "all") ...
        + sum(p.M.*(squeeze(l.phi_up(i,:,:)).*q_up + squeeze(l.phi_down(i,:,:)).*q_down), "all") ...
        - sum((1 - p.M).*squeeze(l.theta(i,:,:)).*e, "all");
end

